# Generated by Django 4.1.7 on 2023-02-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_session',
        ),
    ]
