# Generated by Django 4.1.7 on 2023-02-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_discount_tax_remove_order_amount_item_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10),
        ),
    ]
